# Generated by Django 4.2.5 on 2025-01-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usuario_groups_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nif',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
