# Generated by Django 4.2.5 on 2025-01-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagem_usuario',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
