# Generated by Django 4.2.5 on 2025-02-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usuario_imagem_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carregarrecarga',
            name='codigo_da_recarga',
            field=models.CharField(max_length=300),
        ),
    ]
