# Generated by Django 4.2.5 on 2025-03-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_carregarrecarga_codigo_da_recarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_de_conta',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_do_contador',
            field=models.CharField(max_length=300),
        ),
    ]
